version: '1'
services:
  matrix_alertmanager_bot:
    build:
      context: .
    image: tainguyenbp/matrix-alertmanager-bot:0.4.0
    container_name: matrix_alertmanager_bot
    ports:
      - 8008:8008
      - 3000:3000
    environment:
      APP_PORT: "3000"
      APP_ALERTMANAGER_SECRET: "hgH2K2L4vV6qY8S8ydFtzdUNYYdPrrw9"
      MATRIX_HOMESERVER_URL: "https://alert.hotromaytinhit.tech"
      MATRIX_ROOMS: "matrix-/!ZEgSx45KQufnRf8W:alert.hotromaytinhit.tech"
      MATRIX_USER: "@bot.tainguyenbp:alert.hotromaytinhit.tech"
      MATRIX_TOKEN: "AQeHNqDwpeVsEc3Sz7dypSkTeuZVLRZx"
      MENTION_ROOM: "1"
